server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:32790/eureka/