server:
  port: 9411

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:32790/