server:
  port: 9411

eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
     preferIpAddress: true
	 ip-address: 192.168.99.100
  client:
     serviceUrl:
      defaultZone: http://192.168.99.100:32785/eureka/
server:
   port: 9411
